In [2]:
import pandas as pd

时间窗口
不计算全局数据的总和或平均,而是计算局部移动区间内的数据,核心目的是平滑短期波动,凸显长期趋势

1. rolling 滑动窗口
    - winodw 窗口大小,可传数字3行数据,可传字符3D表3天(按天算中间日期缺失会自动识别)
    - min_periods 最小观测值,如果窗口为3前两行凑不够就会Nan
2. expanding 累计窗口 窗口不断扩大,起点第一行(计算记录最高销售)
3. ewn 指数加权窗口

In [5]:
dates = pd.date_range('2023-01-01', periods=5)
df = pd.DataFrame({'销量': [10, 20, 30, 40, 50]}, index=dates)

df.rolling(2,min_periods=1).mean()

              销量
2023-01-01  10.0
2023-01-02  15.0
2023-01-03  25.0
2023-01-04  35.0
2023-01-05  45.0

In [11]:
'''
销量  历史均值  历史最高
2023-01-01  10  10.0   10.0  <-- (10)/1
2023-01-02  20  15.0   20.0  <-- (10+20)/2
2023-01-03  30  20.0   30.0  <-- (10+20+30)/3
2023-01-04  40  25.0   40.0  <-- (10+20+30+40)/4
2023-01-05  50  30.0   50.0  <-- 每天的计算范围都在扩大
'''
df.expanding().sum()

               销量
2023-01-01   10.0
2023-01-02   30.0
2023-01-03   60.0
2023-01-04  100.0
2023-01-05  150.0

时序数据
pd.Timestamp是pd里定义时间的函数,可代替datetime.datetime

时长数据
pd.Timedelta

时长索引

时序索引
pd.date_range
pd.bdate_range 跳过周六日.实现工作日时间索引序列
时序索引访问

.dt.<>时间访问器
时长数据访问器,频率转换

时间偏移 DateOffset
时间段 Peroid
- 属性
- 方法
- 计算
- 时间段索引

时间操作
- 时区转换
- 时间的格式化
- 时间重采样
- 时间类型间转换 to_period,to_timestamp
- 区间间隔 Interval

In [ ]:
from  datetime import datetime
datetime.now()

datetime.datetime(2026, 7, 28, 17, 10, 59, 193226)